Support Sims 3/4 header mode
actioninja/refpack-rs pull request #1
Opened 2023-03-16 21:33 UTC by chieltbest

The new maxis header mode is the same as Maxis, with the removal of the compressed size u32, and the addition of more flags for decompressed int size / feature flags.
Reference: [Sims 3 Compression](http://simswiki.info/wiki.php?title=Sims_3:DBPF/Compression)

I have found no evidence of these flags used in any Sims 2 packages (these use the old maxis header, so always 0x10FB).

With this a change had to be made to the header length interface to be a function (with decompressed size as an argument) instead of a constant.

I'm not really sure about calling the new header mode 'Maxis2', it works well enough as an internal implementation detail, but suggestions are welcome.

I've also added some integration tests to verify that writing headers and data works in combination with each other for all formats.

2023-03-22 03:22 UTC, actioninja commented
Wow, didn't think I would ever actually get interaction with such a niche tool, hah. Sorry about the slow response, been on a vacation for the past week.
I have a lot of other projects to catch up right now. so I'll get around to reviewing this in the next few days. Looks super clean and I appreciate the unit tests as well!

2023-03-22 16:39 UTC, chieltbest commented
> Sorry about the slow response, been on a vacation for the past week.

No problem, I'm not in any particular hurry so take all the time you need.

As for why this library: I've been wanting to learn rust for a while and my mother kept complaining about the state of current Sims 2 modding tools, so I figured I would make a dbpf library.
Having this awesome library available only cemented that decision further, and it's been really nice to learn about all the rust testing tools and such.

By the way, I'm also working on some performance improvements in the decompression algorithm, and so far I'm up to +400% performance, but sadly it guts a lot of the reading functions so I'll make another pull request once I'm satisfied with it.

2023-03-22 19:22 UTC, actioninja commented
> As for why this library: I've been wanting to learn rust for a while and my mother kept complaining about the state of current Sims 2 modding tools, so I figured I would make a dbpf library.

It's pretty appalling, that was one of my big motivations for initially starting this project and the project it was intended for (https://github.com/actioninja/s2-dbpf), but I never really got it off the ground by falling down the "completeness" hole rather than focusing on skeleton code first and then fleshing it out. Plus the helper crate `binrw` I was using for defining the huge amount of binary formats (that I initially used here as well) was in very heavy development at the time and as a result I was constantly trying to beat it into the shapes I wanted.

And sure, I'm open to any kind of performance improvements. The algorithms themselves were largely lazily lifted from existing rust compression libraries and there's no doubt tons of performance improvements lurking due to the shoddy modifications.

2023-03-22 22:27 UTC, actioninja requested changes
Some minor changes, most of it looks good

2023-03-23 21:24 UTC, chieltbest commented on src/header/mode/maxis2.rs
> +            x => return Err(RefPackError::BadMagic(x)),
Reading the niotso wiki and comparing it with the Sims wiki, it seems that those two formats are actually the same format, so I'll change the new header mode to use flags instead.

So the flags would be: `LR0?000C`
`L` = Large decompressed field size
`R` = Restricted mode (unused)
`?` = Bit that is normally 1, except for large files (so probably just ignore it)
`C` = Compressed size present (I haven't seen this flag used anywhere, so I'm unfamiliar where this field would be placed)
All the other bits would be checked equal to 0 to act as a file magic for automatic format checking

The niotso wiki also states this:
> Note that The Sims Online only recognizes the compressed-size-present flag; the large-files flag and the unknown flag were not introduced until SimCity 4 and Command & Conquer 3.

So these flags should probably also be present in the `TheSims12` header so my plan is to make the `TheSims12` header read using the new header struct with the added compressed size before it.

2023-03-25 22:20 UTC, actioninja commented on src/header/mode/maxis2.rs
> +            x => return Err(RefPackError::BadMagic(x)),
I don't believe any implementation for The Sims 2 or Simcity 4 ever actually read the flags field. JDBPF, DBPF4J (SC4 tools) both just read the 0xFB and 0x10 bytes and swallowed flags. SimPE as well just reads, verifies the two bytes, and swallows the flags.
I *believe* this should be compatible anyways, considering that the flags state seen is the same as reading it as a magic number. It's something I considered doing myself, but didn't want to deal with the potential headache of variable sized headers.

2023-03-28 00:54 UTC, chieltbest commented on src/header/mode/maxis2.rs
> +            x => return Err(RefPackError::BadMagic(x)),
I've re-implemented the header mode as described above, but I've left `TheSims12` as is because it is more restrictive meaning better format detection.

2023-03-28 00:55 UTC, chieltbest commented on src/header/mode/maxis2.rs
> +}
I also added `Hash` in addition to the ones you listed.

2023-03-28 00:57 UTC, chieltbest commented on src/header/mode/maxis2.rs
> +pub struct Maxis2 {
I've renamed it `SimEA` as you suggested, I like it better than `Maxis2` and it reflects the usage well enough.

2023-03-28 01:00 UTC, chieltbest commented on src/header/mode/mod.rs
> +    fn length(decompressed_size: usize) -> usize;
I don't really know of a better way to do this, so let's just go with it as it's good enough.

2023-03-28 06:17 UTC, actioninja approved these changes

2023-03-28 06:32 UTC, merged